name: Release

on:
  push:
    branches:
      - main
      - beta

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14
      - name: Install dependencies and build
        run: |
          npm ci
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GIT_AUTHOR_NAME: kurtrank
          GIT_AUTHOR_EMAIL: kurtrank@gmail.com
          GIT_COMMITTER_NAME: kurtrank
          GIT_COMMITTER_EMAIL: kurtrank@gmail.com
          IS_CI: true
        run: npx semantic-release --extends ./internal-release.config.js
